name: CI Desafio Devops

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonando repositório via Checkout
        uses: actions/checkout@v4

      - name: Configurar Python na maquina
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Instalar dependências do projeto
        run: pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Clonando repositório via Checkout
        uses: actions/checkout@v4

      - name: Configurar Python na maquina
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Instalar dependências do projeto
        run: pip install -r requirements.txt
        
      - name: Rodar testes unitários
        run: python -m unittest discover

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Deploy usando action do Render
        uses: johnbeynon/render-deploy-action@v0.0.3
        with:
          serviceId: srv-d4iv64m3jp1c73cai1s0
          apiKey: ${{ secrets.KEYDEVOPS }}
          clearCache: false

      - name: Deploy Hook no Render
        run: |
          curl -X POST "${{ secrets.HOOK_GUSTAVO }}"
          echo "Deploy enviado ao Render."
